# Generated by Django 4.0.5 on 2022-06-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtzapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='case_name',
            field=models.CharField(max_length=300),
        ),
    ]
