# Generated by Django 4.0.5 on 2022-06-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtzapi', '0002_alter_docket_case_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='case_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='docket',
            name='case_num',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
