# Generated by Django 4.0.5 on 2022-06-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courtzapi', '0004_alter_docketparty_docket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filing',
            name='filer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtzapi.docketparty'),
        ),
    ]
