# Generated by Django 4.0.5 on 2022-06-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courtzapi', '0005_alter_filing_filer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filing',
            old_name='filer',
            new_name='docket_party',
        ),
    ]
